### ISSUE TITLE
Xin bản quyền sử dụng

### ISSUE THREAD

**Issue by tiendung** [phongnt570/UETsegmenter#7]
Hi Phong,

Anh đang viết thư viện https://github.com/telexyz/syll2words, và có một phần mã nguồn từ UETsegmenter nên muốn hỏi em bản quyền để sử dụng. Em đọc https://github.com/telexyz/syll2words/blob/master/README.md để biết thêm chi tiết nhé.

Anh thấy UETsegmenter ko đề LICENSE nên có lẽ là em sẽ cho phép mọi người sử dụng lại mã nguồn mình viết 👍 👍 👍, hoặc có thể ngược lại nên anh muốn hỏi em cho chắc chắn.

Mong em trả lời sớm,

Dũng.

**Comment by phongnt570** [comment]
Hi anh Dũng,

Cảm ơn anh đã sử dụng code của UETsegmenter. Code không có License và có thể được sử dụng lại tùy ý. Tuy nhiên, nếu anh muốn trích dẫn nguồn, anh có thể dẫn 1 đường link đến repo UETsegmenter hoặc đến trang cá nhân của em (http://tuan-phong.com/), nhưng như đã nói ở trên, việc này là không bắt buộc vì code của UETsegmenter không có License :)

Chúc anh thành công với project của mình.

Phong

**Comment by tiendung** [comment]
Cám ơn Phong :)
